services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-postgres}
      DB_PORT: ${DB_PORT:-5432}
    env_file:
      - .env
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: go run cmd/api/main.go
    volumes:
      - .:/code

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: postgres -c log_statement=all
    volumes:
    - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: